services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=info@elyxxa.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-certificates:/letsencrypt"
    restart: unless-stopped
    networks:
      - elyxxa-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - .env

    volumes:
      - .:/app
      - /app/node_modules
      - sqlite-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`notifier.elyxxa.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
    restart: unless-stopped
    networks:
      - elyxxa-network

  # Add Redis for caching and session management if needed
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - elyxxa-network

volumes:
  redis_data:
  traefik-certificates:
  sqlite-data:

networks:
  elyxxa-network:
    driver: bridge
