# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bb78030a5f9fcac6f1d678b7692800d8"
application_url = "https://settlement-sculpture-gets-dk.trycloudflare.com"
embedded = true
name = "alert-notifier"
handle = "alert-notifier"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://settlement-sculpture-gets-dk.trycloudflare.com/auth/callback",
  "https://settlement-sculpture-gets-dk.trycloudflare.com/auth/shopify/callback",
  "https://settlement-sculpture-gets-dk.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
