# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "39f3ee8d6618fa4efed1f38f8726c4a9"
application_url = "https://resulted-eos-guns-philippines.trycloudflare.com"
embedded = true
name = "Notifier"
handle = "notifier-26"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://resulted-eos-guns-philippines.trycloudflare.com/auth/callback",
  "https://resulted-eos-guns-philippines.trycloudflare.com/auth/shopify/callback",
  "https://resulted-eos-guns-philippines.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
