# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "742b948298a33069d6eb11d1c7233982"
application_url = "https://2ad5-144-48-149-102.ngrok-free.app"
embedded = true
name = "Notifier"
handle = "notifier-26"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://2ad5-144-48-149-102.ngrok-free.app/auth/callback",
  "https://2ad5-144-48-149-102.ngrok-free.app/auth/shopify/callback",
  "https://2ad5-144-48-149-102.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
