# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1da8658291502513545729453bcafcc8"
application_url = "https://heritage-individual-won-headquarters.trycloudflare.com"
embedded = true
name = "Notifier"
handle = "notifier-26"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://heritage-individual-won-headquarters.trycloudflare.com/auth/callback",
  "https://heritage-individual-won-headquarters.trycloudflare.com/auth/shopify/callback",
  "https://heritage-individual-won-headquarters.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
