# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b701f522ac64d4c6e496f9c100490356"
application_url = "https://enhancements-england-minnesota-ol.trycloudflare.com"
embedded = true
name = "Notifier"
handle = "notifier-26"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://enhancements-england-minnesota-ol.trycloudflare.com/auth/callback",
  "https://enhancements-england-minnesota-ol.trycloudflare.com/auth/shopify/callback",
  "https://enhancements-england-minnesota-ol.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
