# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc199f6a72533fd8decfbc423ae3448a"
application_url = "https://notifier.elyxxa.com"
embedded = true
name = "Notifier"
handle = "notifier-26"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://notifier.elyxxa.com/auth/callback",
  "https://notifier.elyxxa.com/auth/shopify/callback",
  "https://notifier.elyxxa.com/api/auth/callback"
]

[pos]
embedded = false
